### ISSUE TITLE
hugging face 모델 로드 관련.

### ISSUE THREAD

**Issue by kibeomkim7565** [monologg/KoELECTRA#23]
Pytorch로 하면 잘 불러오는데,
TF에서는 불러오지 못하고 에러가 발생합니다.

ElectraModel.from_pretrained("monologg/koelectra-base-v2-discriminator")
->이거는 잘됨

TFElectraModel.from_pretrained("monologg/koelectra-base-v2-discriminator")
-> 이거는 hugging face에 해당 모델이 없으니 확인해보라고 나옴.

한번 확인부탁드립니다~

**Comment by monologg** [comment]
@kibeomkim7565 

테스팅했을때는 정상적으로 로딩되는 것으로 확인되네요.

혹시 `tensorflow>=2.0` 을 설치하셨는지 확인해주실 수 있나요?
`tensorflow>=2.0` 을 설치하지 않으면 아래와 같은 로그가 나오네요

```
TFElectraModel requires the TensorFlow library but it was not found in your environment. Checkout the instructions on the
installation page: https://www.tensorflow.org/install and follow the ones that match your environment.
```

그럼에도 로딩이 안 되는 것이면 실제 에러 로그 댓글로 부탁드릴게요:)

**Comment by kibeomkim7565** [comment]
> @kibeomkim7565
> 
> 테스팅했을때는 정상적으로 로딩되는 것으로 확인되네요.
> 
> ![Screenshot_20210624-164453](https://user-images.githubusercontent.com/28896432/123223096-910f7d00-d50b-11eb-8453-bab330791bd0.png)
> 
> 혹시 `tensorflow>=2.0` 을 설치하셨는지 확인해주실 수 있나요?
> `tensorflow>=2.0` 을 설치하지 않으면 아래와 같은 로그가 나오네요
> 
> ```
> TFElectraModel requires the TensorFlow library but it was not found in your environment. Checkout the instructions on the
> installation page: https://www.tensorflow.org/install and follow the ones that match your environment.
> ```
> 
> 그럼에도 로딩이 안 되는 것이면 실제 에러 로그 댓글로 부탁드릴게요:)



이렇게나 빨리 답변을 주시다니!!! ㅠㅠ 영광입니다.
동일한 테스트를 저 환경에서 하면,, 저는 안되거든요 ㅠ 아래와 같습니다.



****** 실행 코드 :
from transformers import TFElectraModel
model = TFElectraModel.from_pretrained("monologg/koelectra-base-v2-discriminator")




****** 에러로그 : 
Downloading: 100%|██████████| 487/487 [00:00<00:00, 488kB/s]
Traceback (most recent call last):
  File "C:\Users\kkbyg\anaconda3\envs\acc_cpu\lib\site-packages\transformers\modeling_tf_utils.py", line 588, in from_pretrained
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/kkbyg/PycharmProjects/pythonProject/main.py", line 2, in <module>
    model = TFElectraModel.from_pretrained("monologg/koelectra-base-v2-discriminator")
  File "C:\Users\kkbyg\anaconda3\envs\acc_cpu\lib\site-packages\transformers\modeling_tf_utils.py", line 595, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 'monologg/koelectra-base-v2-discriminator'. Make sure that:

- 'monologg/koelectra-base-v2-discriminator' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'monologg/koelectra-base-v2-discriminator' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.


python-BaseException

Process finished with exit code 1


실행환경 : 
- pip:
    - absl-py==0.13.0
    - astunparse==1.6.3
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==8.0.1
    - colorama==0.4.4
    - cycler==0.10.0
    - filelock==3.0.12
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.32.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==4.5.0
    - joblib==1.0.1
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.2
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.5
    - pillow==8.2.0
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - regex==2021.4.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacremoses==0.0.45
    - scikit-learn==0.21.2
    - scipy==1.7.0
    - sentencepiece==0.1.96
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-cpu==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - tokenizers==0.8.1rc2
    - tqdm==4.61.1
    - transformers==3.3.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.5
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.4.1

**Comment by monologg** [comment]
우선은 아래로 먼저 실행해주실수 있나요? 아래 방법으로 하면 `pytorch_model.bin` 에서 로딩할 것입니다. (torch도 설치해야 합니다)

```python
from transformers import TFElectraModel

model = TFElectraModel.from_pretrained("monologg/koelectra-base-v2-discriminator", from_pt=True)
```

원인은 제가 좀 더 찾아보도록 하겠습니다

**Comment by kibeomkim7565** [comment]
추가적으로, git clone을 통해 local로 올려주신 모델을 다운받은 후, 로딩하는 실험도 해보았으나, save된 shape과 달라서 로딩이 안되는것같습니다 ㅠ

![image](https://user-images.githubusercontent.com/54129380/123361318-ccf91f80-d5a9-11eb-917f-baab1ff232a5.png)

![image](https://user-images.githubusercontent.com/54129380/123361361-de422c00-d5a9-11eb-89b1-00c9280b647a.png)

![image](https://user-images.githubusercontent.com/54129380/123361385-ebf7b180-d5a9-11eb-85d7-9472138dcdc7.png)

**Comment by kibeomkim7565** [comment]
엇.. 이렇게 실시간으로 답변을 주시다니 ㅠ 정말 감사드립니다  pt_model로 불러오는 옵션 말씀주신것 적용해서 해보겠습니다!

**Comment by monologg** [comment]
우선은 transformers 라이브러리 버전에서 생기는 이슈인 것 같네요

`transformers==3.3.1`에서는 저도 동일한 이슈가 발생하네요...
`transformers>=3.5` 부터는 정상 작동을 하네요. 

제가 아마 tf_model로 변환을 `transformers==3.5.1` 로 했던 것으로 기억하는데, 거기에서 기인하는 라이브러리 내부적인 이슈인 것 같습니다.

**Comment by kibeomkim7565** [comment]
다행이네요..!!! 그 finetuning 폴더에 requirment.txt에 transformer==3.3.1로 적혀있거든요!!

그것을 3.5.1로 바꿔주시면 더 좋을것같습니다!

왠지 그 requirement를 따라해야되는 느낌이 있어서 그걸했거든요 ㅠ

그리고 finetune 의 readme.md설명에도 3.3.1로 설명되어있습니다~!

이렇게 실시간으로 신경써주셔서 대단히 감사드립니다!!!

**Comment by monologg** [comment]
finetuning 코드가 pytorch 기준으로 작성되어서 이런 부분이 확인이 되지 못한 거 같습니다.
아마 해당 requirements는 result 재현을 위해서 고정을 해야할 거 같습니다.

https://github.com/huggingface/transformers/commit/70f622fab4dabeb4eab66dd1290ab1bc695a9301# 커밋을 보면 `hf_buchet_url` 을 `v3.5.0`에서 변경하면서 생기는 이슈로 예상이 되네요.

관련하여 테스팅 해보고 공지하도록 하겠습니다.

이슈 제보해주셔서 감사합니다:)
