### ISSUE TITLE
WordPiece Vocabulary 예제 코드 에러

### ISSUE THREAD

**Issue by JeongWoonPark** [monologg/KoELECTRA#9]
예제 코드를 그대로 실행했을 때 아래와 같은 에러가 발생합니다.
```
Traceback (most recent call last):
  File "WordPiece_Vocabulary.py", line 28, in <module>
  File "...\tokenizers\implementations\base_tokenizer.py", line 332, in save
    return self._tokenizer.save(path, pretty)
TypeError
```

에러가 발생하는 함수의 내용은 다음과 같으므로,
```
    def save(self, path: str, pretty: bool = False):
        """ Save the current Tokenizer at the given path

        Args:
            path: str:
                A path to the destination Tokenizer file
        """
        return self._tokenizer.save(path, pretty)
```

인자를 쉼표로 구분하지 말고 한꺼번에 써줘야 합니다.
```
tokenizer.save("./ch-{}-wpm-{}".format(args.limit_alphabet, args.vocab_size))
```

**Comment by monologg** [comment]
@JeongWoonPark 

안녕하세요:)

제가 당시에 해당 예제를 올릴 때 `tokenizers==0.7.0` 을 사용했는데, `0.8.0`으로 가면서 API가 변경된 것 같습니다 (블로그에는 명시를 해놨는데 여기에서 명시하는 것을 깜빡했네요ㅠ)

오류 발견해주셔서 정말 감사합니다!

**Comment by monologg** [comment]
@JeongWoonPark 

내용 반영하여 예제 부분 수정했습니다! 혹시나 이슈가 있으면 다시 오픈해주시면 됩니다:)
